/**
 * Mock Data Seeding
 *
 * Initializes mock data for development/testing.
 * This file is regenerated by the Almadar Compiler when compiling a schema.
 *
 * @packageDocumentation
 */

import { mockDataService, type EntitySchema } from './services/MockDataService.js';
import { logger } from './lib/logger.js';

// Entity schemas are generated by the compiler based on your schema.orb
const entitySchemas: Record<string, EntitySchema> = {
  // Generated entity schemas will be populated here
};

/**
 * Initialize mock data for all entities
 */
export async function initializeMockData(): Promise<void> {
  for (const [entityName, schema] of Object.entries(entitySchemas)) {
    mockDataService.registerSchema(entityName, schema);
    mockDataService.seed(entityName, schema.fields, schema.seedCount || 10);
    logger.info(`Seeded ${schema.seedCount || 10} ${entityName}`);
  }
}
