/**
 * Entity Types
 *
 * TypeScript interfaces for all entities.
 * Auto-generated by Almadar Compiler.
 *
 * @packageDocumentation
 */

/**
 * AtomDemo entity
 */
export interface AtomDemo {
  id: string;
  label: string;
  variant: string;
  size: 'sm' | 'md' | 'lg';
  isDisabled: boolean;
}
/**
 * AtomDemo input (for creation)
 */
export interface AtomDemoInput {
  label: string;
  variant: string;
  size: 'sm' | 'md' | 'lg';
  isDisabled: boolean;
}

/**
 * AtomDemo update (partial)
 */
export type AtomDemoUpdate = Partial<AtomDemoInput>;

/**
 * MoleculeDemo entity
 */
export interface MoleculeDemo {
  id: string;
  name: string;
  category: string;
  searchTerm: string;
}
/**
 * MoleculeDemo input (for creation)
 */
export interface MoleculeDemoInput {
  name: string;
  category: string;
  searchTerm: string;
}

/**
 * MoleculeDemo update (partial)
 */
export type MoleculeDemoUpdate = Partial<MoleculeDemoInput>;

/**
 * Product entity
 */
export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  stock: number;
  category: 'electronics' | 'clothing' | 'food' | 'other';
  status: 'active' | 'draft' | 'archived';
  createdAt: string;
}
/**
 * Product input (for creation)
 */
export interface ProductInput {
  name: string;
  description: string;
  price: number;
  stock: number;
  category: 'electronics' | 'clothing' | 'food' | 'other';
  status: 'active' | 'draft' | 'archived';
}

/**
 * Product update (partial)
 */
export type ProductUpdate = Partial<ProductInput>;

/**
 * Project entity
 */
export interface Project {
  id: string;
  name: string;
  description: string;
  status: 'planning' | 'active' | 'completed' | 'on-hold';
  progress: number;
  budget: number;
  startDate: string;
  endDate: string;
  teamSize: number;
}
/**
 * Project input (for creation)
 */
export interface ProjectInput {
  name: string;
  description: string;
  status: 'planning' | 'active' | 'completed' | 'on-hold';
  progress: number;
  budget: number;
  startDate: string;
  endDate: string;
  teamSize: number;
}

/**
 * Project update (partial)
 */
export type ProjectUpdate = Partial<ProjectInput>;

/**
 * SearchableItem entity
 */
export interface SearchableItem {
  id: string;
  title: string;
  category: 'tech' | 'design' | 'marketing' | 'sales';
  priority: 'low' | 'medium' | 'high';
  isActive: boolean;
}
/**
 * SearchableItem input (for creation)
 */
export interface SearchableItemInput {
  title: string;
  category: 'tech' | 'design' | 'marketing' | 'sales';
  priority: 'low' | 'medium' | 'high';
  isActive: boolean;
}

/**
 * SearchableItem update (partial)
 */
export type SearchableItemUpdate = Partial<SearchableItemInput>;

/**
 * NavItem entity
 */
export interface NavItem {
  id: string;
  label: string;
  path: string;
  icon: string;
}
/**
 * NavItem input (for creation)
 */
export interface NavItemInput {
  label: string;
  path: string;
  icon: string;
}

/**
 * NavItem update (partial)
 */
export type NavItemUpdate = Partial<NavItemInput>;

/**
 * WizardData entity
 */
export interface WizardData {
  id: string;
  step1Data: string;
  step2Data: string;
  step3Data: string;
  currentStep: number;
}
/**
 * WizardData input (for creation)
 */
export interface WizardDataInput {
  step1Data: string;
  step2Data: string;
  step3Data: string;
  currentStep: number;
}

/**
 * WizardData update (partial)
 */
export type WizardDataUpdate = Partial<WizardDataInput>;

/**
 * StateDemo entity
 */
export interface StateDemo {
  id: string;
  currentState: 'loading' | 'empty' | 'error' | 'success';
}
/**
 * StateDemo input (for creation)
 */
export interface StateDemoInput {
  currentState: 'loading' | 'empty' | 'error' | 'success';
}

/**
 * StateDemo update (partial)
 */
export type StateDemoUpdate = Partial<StateDemoInput>;

/**
 * ModalItem entity
 */
export interface ModalItem {
  id: string;
  title: string;
  content: string;
}
/**
 * ModalItem input (for creation)
 */
export interface ModalItemInput {
  title: string;
  content: string;
}

/**
 * ModalItem update (partial)
 */
export type ModalItemUpdate = Partial<ModalItemInput>;

/**
 * ContentItem entity
 */
export interface ContentItem {
  id: string;
  title: string;
  content: string;
  isExpanded: boolean;
}
/**
 * ContentItem input (for creation)
 */
export interface ContentItemInput {
  title: string;
  content: string;
  isExpanded: boolean;
}

/**
 * ContentItem update (partial)
 */
export type ContentItemUpdate = Partial<ContentItemInput>;

/**
 * GameState entity
 */
export interface GameState {
  id: string;
  score: number;
  lives: number;
  level: number;
  isPaused: boolean;
  isGameOver: boolean;
}
/**
 * GameState input (for creation)
 */
export interface GameStateInput {
  score: number;
  lives: number;
  level: number;
  isPaused: boolean;
  isGameOver: boolean;
}

/**
 * GameState update (partial)
 */
export type GameStateUpdate = Partial<GameStateInput>;

/**
 * LayoutDemo entity
 */
export interface LayoutDemo {
  id: string;
  layoutType: 'split' | 'grid' | 'flex' | 'box';
}
/**
 * LayoutDemo input (for creation)
 */
export interface LayoutDemoInput {
  layoutType: 'split' | 'grid' | 'flex' | 'box';
}

/**
 * LayoutDemo update (partial)
 */
export type LayoutDemoUpdate = Partial<LayoutDemoInput>;

/**
 * ContainerDemo entity
 */
export interface ContainerDemo {
  id: string;
  isOpen: boolean;
}
/**
 * ContainerDemo input (for creation)
 */
export interface ContainerDemoInput {
  isOpen: boolean;
}

/**
 * ContainerDemo update (partial)
 */
export type ContainerDemoUpdate = Partial<ContainerDemoInput>;

