/**
 * Card Component
 *
 * A generic card container for displaying content with optional title,
 * subtitle, and action buttons.
 *
 * @generated by Almadar Compiler
 */

import React from 'react';

export interface CardAction {
  label: string;
  onClick: () => void;
  variant?: 'default' | 'primary' | 'danger';
  icon?: string;
  disabled?: boolean;
}

export interface CardProps {
  /** Card title */
  title?: string;
  /** Card subtitle or description */
  subtitle?: string;
  /** Image URL to display at top of card */
  image?: string;
  /** Action buttons to display in card footer */
  actions?: CardAction[];
  /** Card content */
  children?: React.ReactNode;
  /** Click handler for the entire card */
  onClick?: () => void;
  /** Additional CSS classes */
  className?: string;
}

/**
 * Card component for displaying content in a contained box
 */
export function Card({
  title,
  subtitle,
  image,
  actions,
  children,
  onClick,
  className = '',
}: CardProps) {
  const isClickable = !!onClick;

  return (
    <div
      className={`
        bg-white dark:bg-gray-800
        border border-gray-200 dark:border-gray-700
        rounded-lg shadow-sm
        ${isClickable ? 'cursor-pointer hover:shadow-md transition-shadow' : ''}
        ${className}
      `}
      onClick={onClick}
      role={isClickable ? 'button' : undefined}
      tabIndex={isClickable ? 0 : undefined}
      onKeyDown={isClickable ? (e) => e.key === 'Enter' && onClick?.() : undefined}
    >
      {/* Image */}
      {image && (
        <div className="aspect-video w-full overflow-hidden rounded-t-lg">
          <img
            src={image}
            alt={title || 'Card image'}
            className="w-full h-full object-cover"
          />
        </div>
      )}

      {/* Content */}
      <div className="p-4">
        {/* Header */}
        {(title || subtitle) && (
          <div className="mb-3">
            {title && (
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
                {title}
              </h3>
            )}
            {subtitle && (
              <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
                {subtitle}
              </p>
            )}
          </div>
        )}

        {/* Children */}
        {children && <div className="text-gray-700 dark:text-gray-300">{children}</div>}

        {/* Actions */}
        {actions && actions.length > 0 && (
          <div className="flex flex-wrap gap-2 mt-4 pt-4 border-t border-gray-200 dark:border-gray-700">
            {actions.map((action, index) => (
              <button
                key={index}
                onClick={(e) => {
                  e.stopPropagation();
                  action.onClick();
                }}
                disabled={action.disabled}
                className={`
                  px-3 py-1.5 text-sm font-medium rounded-md
                  transition-colors
                  ${action.variant === 'primary'
                    ? 'bg-blue-600 text-white hover:bg-blue-700 disabled:bg-blue-400'
                    : action.variant === 'danger'
                    ? 'bg-red-600 text-white hover:bg-red-700 disabled:bg-red-400'
                    : 'bg-gray-100 text-gray-700 hover:bg-gray-200 dark:bg-gray-700 dark:text-gray-200 dark:hover:bg-gray-600'
                  }
                  disabled:cursor-not-allowed
                `}
              >
                {action.label}
              </button>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

export default Card;
